# Copyright 2023 New Relic Corporation. All rights reserved.
# SPDX-License-Identifier: New Relic Pre-Release

name: Go Security Agent CI

on: [push,pull_request]

jobs:
  go-agent-v3:
    runs-on: ubuntu-latest
  
    strategy:
      # if one test fails, do not abort the rest
      fail-fast: false
      matrix:
        include:
          - go-version: 1.17.x
            dirs: instrumentation/csec_antchfx_htmlquery
            extratesting: [v1.3.0, v1.2.0]
            package: "github.com/antchfx/htmlquery"
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Checkout Code
      uses: actions/checkout@v1

    - name: Run Tests
      run: bash ./build-script.sh
      with:
        EXTRATESTING: ${{ matrix.extratesting }}
      env:
        DIRS: ${{ matrix.dirs }}
        PACKAGE: ${{ matrix.package }}
        PIN: ${{ matrix.pin }}