# Copyright 2023 New Relic Corporation. All rights reserved.
# SPDX-License-Identifier: New Relic Pre-Release

name: Go Security Agent CI

on: [push,pull_request]

jobs:
  go-agent-v3:
    runs-on: ubuntu-latest
  
    strategy:
      # if one test fails, do not abort the rest
      fail-fast: false
      matrix:
        include:
          - go-version: 1.19.x
            dirs: instrumentation/csec_antchfx_htmlquery
            extratesting: "v1.3.0,v1.2.0,v1.1.0"
            package: "github.com/antchfx/htmlquery"          
          - go-version: 1.19.x
            dirs: instrumentation/csec_ldap_v3
            extratesting: "v3.0.0,v3.1.0,v3.2.0,v3.3.0,v3.4.0"
            package: "github.com/go-ldap/ldap/v3"
          - go-version: 1.19.x
            dirs: instrumentation/csec_mongodb_mongo
            extratesting: "v1.12.0"
            package: "go.mongodb.org/mongo-driver/mongo"
          - go-version: 1.19.x
            dirs: instrumentation/csec_robertkrimen_otto  
            extratesting: "v0.1.0,v0.2.0"
            package: "github.com/robertkrimen/otto"
   
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Checkout Code
      uses: actions/checkout@v1

    - name: Run Tests
      run: bash ./build-script.sh
      env:
        DIRS: ${{ matrix.dirs }}
        PACKAGE: ${{ matrix.package }}
        PIN: ${{ matrix.pin }}
        EXTRATESTING: ${{ matrix.extratesting }}